apiVersion: v1
kind: Pod
metadata:
  name: ntp-pod4
spec:
  containers:
  - name: ntp-container
    image: yahyadaoudi/servers:latest
    volumeMounts:
    - name: config-volume
      mountPath: /etc/ntp.conf
      subPath: ntp.conf
    ports:
    - containerPort: 1234
    securityContext:
      capabilities:
        add:
        - SYS_TIME   
        - SYS_RESOURCE
  imagePullPolicy: Never
  volumes:
  - name: config-volume
    configMap:
      name: ntp-config

